[package]
name = "day24"
version = "0.1.0"
authors = ["Fabian Peternek <f.peternek@fapet.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
